<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EMarket.Application\eMarket.Application.csproj" />
    <ProjectReference Include="..\EMarket.Domain\eMarket.Domain.csproj" />
    <ProjectReference Include="..\EMarket.SharedKernel\eMarket.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
